from tkinter import filedialog
import tkinter as tk
from tkinter import *
from textwrap import fill
from cProfile import label
from bs4 import BeautifulSoup
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options
